name: coffe2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.1.1
  flutter_fortune_wheel: ^1.3.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  flutter_rating_bar: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0


flutter_native_splash:
  color: "#401E19"
  image: assets/logo/logo.png
  color_dark: "#401E19"
  image_dark: assets/logo/logo.png

  android_12:
    image: assets/logo/logo.png
    icon_background_color: "#401E19"
    image_dark: assets/logo/logo.png
    icon_background_color_dark: "#401E19"

  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/logo/logo.png
    - assets/images/
